Update parser.ts
The ord() introduces the following error: 
TypeError: ord() expected string of length 1, but int found

So this change is to remove ord()